In [1]:
# Linux
import torch
if torch.cuda.is_available():
	print("Cuda ready!")
	device = "cuda"
else:
	print("Cuda driver not installed, device set to CPU")
	device = "cpu"

Cuda ready!


In [4]:
test= ['a', 'b', 'c', 'd']
tt= dict.fromkeys(test, [0])
tt

{'a': [0], 'b': [0], 'c': [0], 'd': [0]}

In [5]:

friends= ["muzi", "ryan", "frodo", "neo"] 
gifts= ["muzi frodo", "muzi frodo", "ryan muzi", "ryan muzi", "ryan muzi", "frodo muzi", "frodo ryan", "neo muzi"] 

In [22]:
dbd_2= dict.fromkeys(friends, [0, ])
dbd= {"muzi": [0], "ryan": [0], "frodo": [0], "neo": [0]}
dbd_2==dbd

True

In [20]:
dbd= dict.fromkeys(friends, [0, ])
dbd

{'muzi': [0], 'ryan': [0], 'frodo': [0], 'neo': [0]}

In [21]:
dbd= {"muzi": [0], "ryan": [0], "frodo": [0], "neo": [0]}
dbd

{'muzi': [0], 'ryan': [0], 'frodo': [0], 'neo': [0]}

In [23]:

for x in gifts: 
    give, save = x.split()
    dbd[give][0]+= 1 
    dbd[save][0]-= 1 
    dbd[give].append(save)
dbd
    

{'muzi': [-3, 'frodo', 'frodo'],
 'ryan': [2, 'muzi', 'muzi', 'muzi'],
 'frodo': [0, 'muzi', 'ryan'],
 'neo': [1, 'muzi']}

In [25]:
def solution(friends, gifts): 
    index= {friend: [0] for friend in friends}
    answer= {friend: 0 for friend in friends}
    
    for x in gifts: 
        give, receive = x.split()
        index[give][0]+= 1 
        index[receive][0]-= 1 
        index[give].append(receive)
        
    for x in range(len(friends)-1): 
        for y in range(x+1, len(friends)): 
            a= index[friends[x]].count(friends[y])
            b= index[friends[y]].count(friends[x])
            if a==b: 
                if index[friends[x]][0]>index[friends[y]][0]:
                    answer[friends[x]]+= 1
                elif index[friends[x]][0]<index[friends[y]][0]:
                    answer[friends[y]]+= 1
            elif a>b: 
                answer[friends[x]]+= 1
            else: 
                answer[friends[y]]+= 1
    return max(answer.values())
        

In [26]:

friends= ["muzi", "ryan", "frodo", "neo"] 
gifts= ["muzi frodo", "muzi frodo", "ryan muzi", "ryan muzi", "ryan muzi", "frodo muzi", "frodo ryan", "neo muzi"] 

In [27]:
solution(friends, gifts)

2

In [29]:
import torch

In [37]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [40]:
t.shape

torch.Size([4, 3])

In [50]:
N= int(input())
npt={}
for x in range(N):
    a= input().split()
    npt.update({int(a[0]): [int(a[1]), int(a[2])]})
print(npt)

{2: [10, 4], 1: [40, 2], 5: [4, 2]}


In [51]:
npt2= npt

In [55]:
npt2= dict(sorted(npt2.items()))

In [56]:
npt2

{1: [40, 2], 2: [10, 4], 5: [4, 2]}

In [59]:
x= [1, 2]
t= x[:0]
t

[]

In [62]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(x_train)
print(x_train.shape)


print(y_train)
print(y_train.shape)


tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [63]:
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W) 

tensor([0.], requires_grad=True)


In [66]:
b= torch.zeros(1, requires_grad= True) 


In [69]:
y_pred = x_train * W + b
print(y_pred)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [71]:
loss= torch.mean((y_train-y_pred)**2)
loss

tensor(18.6667, grad_fn=<MeanBackward0>)

In [72]:
optimizer= optim.SGD([W, b], lr= 0.01)
# optim.SGD(model.parameters(), lr= 0.01)

In [73]:
optimizer.zero_grad()
loss.backward()
optimizer.step()

In [74]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))


Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

In [75]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)

In [76]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])


In [77]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)


In [78]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 


In [79]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [80]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 


훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [81]:
print(list(model.parameters()))


[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


In [116]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__()
        self.linear1 = nn.Linear(3, 3) # 단순 선형 회귀이므로 input_dim=1, output_dim=1.
        self.linear2= nn.Linear(3, 1)
        self.relu= nn.ReLU()

    def forward(self, x):
        x= self.linear1(x) 
        x= self.relu(x) 
        x= self.linear2(x) 

        return x


In [117]:
model = LinearRegressionModel()

In [118]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.5644,  0.3579,  0.1613],
         [ 0.5476,  0.3811, -0.5260],
         [-0.5489, -0.2785,  0.5070]], requires_grad=True),
 Parameter containing:
 tensor([-0.0962,  0.2471, -0.2683], requires_grad=True),
 Parameter containing:
 tensor([[ 0.5665, -0.2443,  0.4330]], requires_grad=True),
 Parameter containing:
 tensor([0.0068], requires_grad=True)]

In [119]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])


In [120]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3) 

In [121]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 32594.255859
Epoch  100/2000 Cost: 30203.275391
Epoch  200/2000 Cost: 29591.871094
Epoch  300/2000 Cost: 29558.113281
Epoch  400/2000 Cost: 29524.261719
Epoch  500/2000 Cost: 29490.375000
Epoch  600/2000 Cost: 29456.474609
Epoch  700/2000 Cost: 29422.574219
Epoch  800/2000 Cost: 29388.681641
Epoch  900/2000 Cost: 29354.800781
Epoch 1000/2000 Cost: 29320.933594
Epoch 1100/2000 Cost: 29287.083984
Epoch 1200/2000 Cost: 29253.250000
Epoch 1300/2000 Cost: 29219.443359
Epoch 1400/2000 Cost: 29185.650391
Epoch 1500/2000 Cost: 29151.880859
Epoch 1600/2000 Cost: 29118.134766
Epoch 1700/2000 Cost: 29084.406250
Epoch 1800/2000 Cost: 29050.699219
Epoch 1900/2000 Cost: 29017.015625
Epoch 2000/2000 Cost: 28983.355469


In [138]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader, Dataset

In [139]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])


In [140]:
dataset= TensorDataset(x_train, y_train)

In [141]:
dataLoader= DataLoader(dataset, batch_size= 2, shuffle= True)

In [142]:
for i, data in enumerate(dataLoader): 
    print(i, data)

0 [tensor([[73., 80., 75.],
        [89., 91., 90.]]), tensor([[152.],
        [180.]])]
1 [tensor([[ 93.,  88.,  93.],
        [ 96.,  98., 100.]]), tensor([[185.],
        [196.]])]
2 [tensor([[73., 66., 70.]]), tensor([[142.]])]


In [143]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__()
        self.linear1 = nn.Linear(3, 3)
        self.linear2= nn.Linear(3, 1)
        self.relu= nn.ReLU()

    def forward(self, x):
        x= self.linear1(x) 
        x= self.relu(x) 
        x= self.linear2(x) 

        return x 
model= LinearRegressionModel()
#.todevice()

print(model)

LinearRegressionModel(
  (linear1): Linear(in_features=3, out_features=3, bias=True)
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (relu): ReLU()
)


In [144]:
optimizer = optim.SGD(model.parameters(), lr=5e-4) 

epochs= 1000 
for epoch in range(epochs+1): 
    for idx, batch in enumerate(dataLoader): 
        x, y_true= batch 
        y_pred= model(x) 

        loss= F.mse_loss(y_pred, y_true)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step() 

        if epoch%50== 0: 
            print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, epochs, idx, len(dataLoader), loss.item()))

Epoch    0/1000 Batch 0/3 Cost: 28706.398438
Epoch    0/1000 Batch 1/3 Cost: 29275.015625
Epoch    0/1000 Batch 2/3 Cost: 32323.255859
Epoch   50/1000 Batch 0/3 Cost: 21846.726562
Epoch   50/1000 Batch 1/3 Cost: 21202.837891
Epoch   50/1000 Batch 2/3 Cost: 24345.175781
Epoch  100/1000 Batch 0/3 Cost: 16312.181641
Epoch  100/1000 Batch 1/3 Cost: 15699.826172
Epoch  100/1000 Batch 2/3 Cost: 18382.910156
Epoch  150/1000 Batch 0/3 Cost: 13074.811523
Epoch  150/1000 Batch 1/3 Cost: 14549.783203
Epoch  150/1000 Batch 2/3 Cost: 6396.157715
Epoch  200/1000 Batch 0/3 Cost: 9199.960938
Epoch  200/1000 Batch 1/3 Cost: 11125.064453
Epoch  200/1000 Batch 2/3 Cost: 5601.076660
Epoch  250/1000 Batch 0/3 Cost: 3268.133545
Epoch  250/1000 Batch 1/3 Cost: 10108.716797
Epoch  250/1000 Batch 2/3 Cost: 8062.455078
Epoch  300/1000 Batch 0/3 Cost: 2102.921875
Epoch  300/1000 Batch 1/3 Cost: 7958.129883
Epoch  300/1000 Batch 2/3 Cost: 6154.340820
Epoch  350/1000 Batch 0/3 Cost: 3210.430176
Epoch  350/1000 Bat

In [148]:
# Dataset 상속
class CustomDataset(Dataset): 
  def __init__(self):
    self.x_data = [[73, 80, 75], 
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y


In [149]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)


In [150]:
for i, data in enumerate(dataloader): 
    print(i, data)

0 [tensor([[73., 66., 70.],
        [93., 88., 93.]]), tensor([[142.],
        [185.]])]
1 [tensor([[ 89.,  91.,  90.],
        [ 96.,  98., 100.]]), tensor([[180.],
        [196.]])]
2 [tensor([[73., 80., 75.]]), tensor([[152.]])]


In [147]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))


Epoch    0/20 Batch 1/3 Cost: 307.521484
Epoch    0/20 Batch 2/3 Cost: 770.384033
Epoch    0/20 Batch 3/3 Cost: 303.686584
Epoch    1/20 Batch 1/3 Cost: 709.626465
Epoch    1/20 Batch 2/3 Cost: 306.868805
Epoch    1/20 Batch 3/3 Cost: 425.271667
Epoch    2/20 Batch 1/3 Cost: 463.057312
Epoch    2/20 Batch 2/3 Cost: 613.905212
Epoch    2/20 Batch 3/3 Cost: 302.279938
Epoch    3/20 Batch 1/3 Cost: 707.577026
Epoch    3/20 Batch 2/3 Cost: 270.127716
Epoch    3/20 Batch 3/3 Cost: 499.929382
Epoch    4/20 Batch 1/3 Cost: 705.950684
Epoch    4/20 Batch 2/3 Cost: 306.022552
Epoch    4/20 Batch 3/3 Cost: 428.258057
Epoch    5/20 Batch 1/3 Cost: 306.195709
Epoch    5/20 Batch 2/3 Cost: 768.948303
Epoch    5/20 Batch 3/3 Cost: 299.779724
Epoch    6/20 Batch 1/3 Cost: 703.929565
Epoch    6/20 Batch 2/3 Cost: 462.845276
Epoch    6/20 Batch 3/3 Cost: 115.116760
Epoch    7/20 Batch 1/3 Cost: 305.675507
Epoch    7/20 Batch 2/3 Cost: 702.860840
Epoch    7/20 Batch 3/3 Cost: 430.544769
Epoch    8/20 Ba